### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by ace214** [openlilylib-resources/lily-fonts#10]
Hi-

Not sure if this is still active, but I get a 404 Error when trying to download the fonts:

Downloading font catalog from https://fonts.openlilylib.org ...
An error occured while accessing the catalog:
HTTP Error 404: Not Found

I assume this is related to the site moving.

**Comment by uliska** [comment]
Indeed. This script is only functional with the local option now. Of course I should have made that explicit (and changed the tool). Sorry.

**Comment by fedelibre** [comment]
I've tried again this script after several time and besides the need of downloading the fonts first and then using --local, it didn't work because it used the wrong path for my lilypond installation (lilypond.org package installed in ~/.local).

Anyway, I think this script is going to be replaced by the new Frescobaldi feature which allows to install (by symlink) and preview alternative music fonts, which is way easier.
https://github.com/frescobaldi/frescobaldi/pull/1075

**Comment by uliska** [comment]
Indeed. This will be obsolete, and if it doesn't work properly I don't see *much* reason to fix it. Of course it would be good to have a cheap CLI solution without the Frescobaldi overhead, but I'm not going to invest my time in it.
